services:
  web:
    build:
      context: ../../
      dockerfile: operation/Docker/dockerfile
    ports:
      - "3000:80"
    image: kausheekraj/trend-store-nginx:latest
    container_name: Trend-store
