apiVersion: apps/v1
kind: Deployment
metadata:
  name: trendstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trendstore
  template:
    metadata:
      labels:
        app: trendstore
    spec:
      containers:
        - name: trendstore
          image: trendstore-nginx:latest
          ports:
            - containerPort: 3000
